import Head from 'next/head';
import { useState } from 'react'

import TopNav from '../components/TopNav';
import NavDrawer from '../components/NavDrawer';
import NavDrawerItem from '../components/NavDrawerItem';

import { AiOutlineHeart, AiFillFileText, AiFillCamera, AiFillHome } from 'react-icons/ai';
import { RiGalleryFill } from 'react-icons/ri'

export default function ContentPage({ pageComponent, title }) {

    const [drawerIsOpen, setDrawerIsOpen] = useState(false);

    return (
        <div className='min-h-screen'>
            <Head>
                <title>{title}</title>
                <meta
                    name="description"
                    content="A photography portfolio for web generated by create next app. Uses TailwindCSS." />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <TopNav
                    title={'Your Name'}
                    onBurgerMenuClicked={() => setDrawerIsOpen(!drawerIsOpen)}
                    subcomponents={
                        [
                            <a key={2} className='font-medium' href='#'>Contact</a>,
                            <AiOutlineHeart key={3} className='text-2xl' />
                        ]
                    } />

                {/** Main Content */}
                <div>

                    {drawerIsOpen ?
                        <NavDrawer
                            items={
                                [
                                    <NavDrawerItem
                                        key={0}
                                        icon={<AiFillHome />}
                                        link={<a href='/'>Home</a>}
                                    />,
                                    <NavDrawerItem
                                        key={1}
                                        icon={<RiGalleryFill />}
                                        link={<a href='/Gallery'>Gallery</a>}
                                    />,
                                    <NavDrawerItem
                                        key={2}
                                        icon={<AiFillFileText />}
                                        link={<a href='#'>Resume</a>}
                                    />,
                                    <NavDrawerItem
                                        key={3}
                                        icon={<AiFillCamera />}
                                        link={<a href='/#services'>Services</a>}
                                    />
                                ]
                            }
                        />
                        : null}
                </div>

                {pageComponent}

            </main>

        </div>
    );
}