import Head from 'next/head';
import Image from 'next/image';
import { AiFillInstagram, AiFillLinkedin, AiFillYoutube, AiOutlineMenu } from 'react-icons/ai';
import rainbow from '../public/photos/rainbow.png'

//  Custom Tailwind Components
import TopNav from '../components/TopNav';
import TextButton from "../components/TextButton";

export default function Home() {
  return (
    <div className='dark:bg-slate-800 dark:text-white min-h-screen'>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='px-5'>
        <section>
          {/** Main Navigation */}
          <TopNav subcomponents={
            [
              <TextButton text='Resume' />,
              <TextButton text='Contact' />
            ]
          } />

          {/** Content Body */}
          <div className='max-w-2xl m-auto'>
            <Image className='m-auto' src={rainbow} />
            {/** Bio */}
            <div className='text-center max-w-xl m-auto'>

              <h2 className='text-3xl font-medium leading-10 py-5'>
                Ian Skelskey
              </h2>
              <p className='leading-10'>
                My name is Ian Skelskey. I am a software engineering student at Arizona State University graduating in Summer of 2023.
              </p>
            </div>

            {/** Social Links */}
            <div className='text-5xl flex justify-center gap-16 text-slate-600 py-5'>
              <AiFillInstagram />
              <AiFillLinkedin />
              <AiFillYoutube />
            </div>
          </div>

        </section>
      </main>

    </div>
  )
}
