import Head from 'next/head';
import Image from 'next/image';
import { AiFillInstagram, AiFillLinkedin, AiFillYoutube, AiOutlineHeart, AiFillFileText, AiFillCamera } from 'react-icons/ai';
import { RiGalleryFill } from 'react-icons/ri'
import rainbow from '../public/photos/iceland/rainbow.png'
import church from '../public/photos/iceland/church.png'

import { useState } from 'react'

//  Custom Tailwind Components
import TopNav from '../components/TopNav';
import ContentCard from '../components/ContentCard';
import ServicesCard from '../components/ServicesCard';
import NavDrawer from '../components/NavDrawer';
import NavDrawerItem from '../components/NavDrawerItem';

/**
 * 
 * @returns A portfolio web application.
 */
export default function Portfolio() {

  const [drawerIsOpen, setDrawerIsOpen] = useState(false);

  return (
    <div className='min-h-screen'>
      <Head>
        <title>Your Name - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TopNav
          title={'Your Name'}
          onBurgerMenuClicked={() => setDrawerIsOpen(!drawerIsOpen)}
          subcomponents={
            [
              <a key={2} className='font-medium' href='#'>Contact</a>,
              <AiOutlineHeart key={3} className='text-2xl' />
            ]
          } />

        {/** Main Content */}
        <div>

          {drawerIsOpen ?
            <NavDrawer
              items={
                [
                  <NavDrawerItem
                    key={1}
                    icon={<RiGalleryFill />}
                    link={<a href='#'>Gallery</a>}
                  />,
                  <NavDrawerItem
                    key={2}
                    icon={<AiFillFileText />}
                    link={<a href='#'>Resume</a>}
                  />,
                  <NavDrawerItem
                    key={3}
                    icon={<AiFillCamera />}
                    link={<a href='#'>Services</a>}
                  />
                ]
              }
            />
            : null}

          <h1>Your Name Photography</h1>

          <ContentCard
            title='“Photography is the art of making memories tangible.”'
            text='- Destin Sparks'
            image={<Image src={rainbow} />}
            dark={false}
          />
          <ContentCard
            title='Title Text Card'
            text='Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              Morbi vel nisl at velit ultricies ornare ac ac libero.
              Sed ut diam non est egestas hendrerit sed ullamcorper nisl.
              Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
              Nunc tempor blandit risus. Nunc lacus mi, tempus sit amet nisi non, rutrum imperdiet nunc.'
            image={<Image src={church} />}
            dark={true}
          />
          <div id='services'>
            <ServicesCard />
          </div>


          {/** Social Links */}
          <div className='text-5xl flex justify-center gap-16 text-neutral-600 py-5'>
            <AiFillInstagram />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
        </div>

      </main>

    </div>
  )
}
